[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pyusb",
    "docopt",
    "pycryptodome",
    "unicorn",
    "colorama",
    "usb",
    "capstone",
    "keystone-engine",
]
build-backend = "setuptools.build_meta"
