[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name="mtkclient"
version="1.6.3"
dependencies = [
    "pyusb",
    "pycryptodome",
    "colorama",
    "shiboken6", 
    "pyside6",
    "mock"
]
